### PR TITLE
tests: fix with Python 3.10 (changed exception messages)

### PR DESCRIPTION
**Pull request by sbraz**
Hi,
Tests need a few small adjustments to pass with Python 3.10.

I guess you could add Python 3.10 it to your CI (and make it non-fatal) but I don't know how Circle CI works so I did not attempt to do it.

### CODE REVIEW

**Comment by cjw296** [comment]
Fantastic, thanks!

**Comment by cjw296** [comment]
@sbraz - apologies, but I've had to revert this as CircleCI aren't ready for Python 3.10 yet:
https://github.com/CircleCI-Public/cimg-python/issues/91

**Comment by sbraz** [comment]
Hi @cjw296
I have tested 3.8, 3.9 and 3.10 on Gentoo and backported the patch there. I can understand reverting the attempt to add 3.10 CI but couldn't we keep this patch?

**Comment by cjw296** [comment]
I'm afraid not: I operate a "100% code coverage" policy on this repo, which is why your PR failed its tests.
I shouldn't have merged, but I didn't realise CircleCI had dropped support for pre-releases of Python.

Feel free to signal boost this tweet if you'd like to see this resolved sooner: https://twitter.com/chriswithers13/status/1429163506142781444

**Comment by sbraz** [comment]
OK I understand, can we at least open an issue or something to keep track of the status of Python 3.10 support?

**Comment by cjw296** [comment]
@sbraz - what would be great is if you could submit those patches as new PR.
Apologies, I know it's duplicate work, but I figure it might be easier than trying to work out how to resurrect this one!

**Comment by cjw296** [comment]
Oh, also feel free to upvote https://ideas.circleci.com/images/p/support-beta-and-rc-versions

**Pull request merged**
