### PR TITLE
matched/missing_from_expected/missing_from_actual attributes

### PR DESCRIPTION
**Pull request by wimglenn**
Will proceed with MappingComparison too if this general approach looks ok to you?

### CODE REVIEW

**Comment by cjw296** [comment]
Yeah, looks great!
Careful on `matched`, though, does that include items which were present but in the wrong order?
Just throwing this out as an idea, not 100% on the names: how about `in_expected_and_actual` for what I suspect is currently in `matched` and `matched` for items that are present in both as well as being in the correct order?

Only other concern would be memory usage when these are using in situations like this:
`SequenceComparison(1, 1000, partial=True) == list(range(1_000_000_000))`
...but I think we could mitigate that with a `record=False` param that could be added later if needed.

**Comment by wimglenn** [comment]
Regarding memory usage, it looks like the "other" is already copied already https://github.com/Simplistix/testfixtures/blob/ba447e6a76f8915c3609382e3665e13147b3b224/testfixtures/comparison.py#L871 .. or was the concern that a reference will be held even after the comparison is finished?

**Comment by cjw296** [comment]
Concern was about the reference hosting, but you're right, the initial copy will also consume a lot of memory, and that can't be safely avoided. Let's not worry about the memory usage now, there's reasonable mitigations that can be applied later, should it cause problems for folk.

**Comment by wimglenn** [comment]
Hmm.  OK, I started looking at `in_expected_and_actual` + `matched` but not really sure how it was intended to work with partial, is this current behavior of the `SequenceComparison` considered correct or bugged? I thought "partial" indicated a subsequence check but it does not seem to be the case?

```
>>> from testfixtures.comparison import SequenceComparison as S
>>> s = S(0,1,   3,2,    4,      3,2,5,partial=1)
>>> s == (0,1,-1,3,2,3,2,4,2,5,3,3,2,5)
False
```

**Comment by cjw296** [comment]
Yeah, that looks like a bug. PR to fix would be very welcome...

**Comment by cjw296** [comment]
Minimal reproducer for bug is:
```
SequenceComparison(1, 2, 1, partial=True) == (1, 1, 2, 1)
```

**Comment by cjw296** [comment]
Fixed in 8ce4a47.

What's wimpy?

**Comment by wimglenn** [comment]
Just my random grab bag of helpers. This is the [`is_subsequence`](https://github.com/wimglenn/wimpy/blob/4e8ebe4e7052d88c9f88ac7dcaa1b587cc2cf86e/wimpy/util.py#L110-L117) impl.

**Comment by cjw296** [comment]
Cool, yeah, the real fun comes when you want to show an explanation of what was different, and when you optionally support unordered...

**Comment by cjw296** [comment]
@wimglenn - what's happening on this one?

**Comment by wimglenn** [comment]
I'm revisiting it now. To clarify your suggestion for `matched` and `in_expected_and_actual` names, after a `SequenceComparison(0, 1, 2, 3, 4)` with `[0, 1, 3]` then you would wanted `s.matched == [0, 1]` and `s.in_expected_and_actual == [0, 1, 3]`, is that right?

**Comment by cjw296** [comment]
> I'm revisiting it now. To clarify your suggestion for `matched` and `in_expected_and_actual` names, after a `SequenceComparison(0, 1, 2, 3, 4)` with `[0, 1, 3]` then you would wanted `s.matched == [0, 1]` and `s.in_expected_and_actual == [0, 1, 3]`, is that right?

@wimglenn - yep, that sounds right.

**Comment by wimglenn** [comment]
@cjw296  what about a sequence comparison when `partial=True` was used? Should `missing_from_expected` always be an empty list in that case? Or should we put the "ignored" items in there too?

**Comment by cjw296** [comment]
> @cjw296 what about a sequence comparison when `partial=True` was used? Should `missing_from_expected` always be an empty list in that case? Or should we put the "ignored" items in there too?

For `SequenceComparison(0, 1, 2, 3, 4, partial=True)` with `[0, 1, 3]` I would expected `missing_from_expected` to be `[2, 4]` and `ignored` to be empty.

Don't forget about ordered too ;-)

**Comment by cjw296** [comment]
I suspect the semantics are already there, hopefully no cases are missing. I believe you're after the results of those in attributes as well as in the message, right?

**Comment by wimglenn** [comment]
@cjw296  Did you mean to say that `missing_from_actual` would be `[2, 4]`?

**Comment by cjw296** [comment]
Updated the comment.

**Comment by wimglenn** [comment]
@cjw296  Do you mean there should be an "ignored" attribute aswell? So that the groups should match the groupings that compare's message displays? I'm still unsure what result is best for the partial case (consider `SequenceComparison(0,1,2,partial=True) ==  [9,0,9,1,9,2]`

**Comment by cjw296** [comment]
So:

```
>>> s = SequenceComparison(0,1,2,partial=True)
>>> s == [9,0,9,1,9]
False
>>> s

<SequenceComparison(ordered=True, partial=True)(failed)>
ignored:
[9, 9, 9]

same:
[0, 1]

expected:
[2]

actual:
[]
</SequenceComparison(ordered=True, partial=True)>
```

Gives:

matched = [0, 1]
expected = [2]
actual = []
ignored = [9, 9, 9]
``` 

I'm not wedded on the names ;-)

**Comment by cjw296** [comment]
@wimglenn - any news on this?

**Comment by wimglenn** [comment]
This is kind of stuck. The `SequenceComparison` instance itself holds all the state we need to do this easily enough, but the `MappingComparison` class does not.

Instead it uses the [`mapping_differences`](https://github.com/Simplistix/testfixtures/blob/a7c9628f69fcf8175c6106cc6a508414dcdd06ab/testfixtures/comparison.py#L1056-L1061), which is just a string returned by `compare(..., raises=False)`, and then produces a message based on the `mapping_differences.split('\n\n')`. All the state we need lives inside the `CompareContext` which is not accessible. 

It will not be possible without a significant refactor and I don't have the cycles for that right now, so feel free to close the PR...

**Comment by cjw296** [comment]
Sorry about that, I can see what you mean. If this becomes pressing, we can take another stab at it...

**Pull request closed without merging**
