### PR TITLE
fix typo in LogCapture

### PR DESCRIPTION
**Pull request by zolyfarkas-fb**

### CODE REVIEW

**Comment by cjw296** [comment]
Looks like CircleCI is having some issues. Would you mind rebasing this to lose the merge commit and also lose the [fix] prefix for the commit? (that's not a pattern I use, as you'll see from all the other commits in this repo)

**Comment by zolyfarkas-fb** [comment]
@cjw296 changed the commit message. CI is doing this since yesterday, I wasn't able to see the results yet...

**Comment by cjw296** [comment]
https://github.com/Simplistix/testfixtures/pull/142 is working, can you try another force push to this branch?
Failing that, perhaps close this PR and open another?

**Comment by zolyfarkas-fb** [comment]
I had to give circle-ci full access to all my public repos, which is a bit excessive to say at least... will revoke the access after I am done with this work. The other ci tools I used don't require this...

**Comment by cjw296** [comment]
I don't think that was required. CircleCIs status page indicated they were having github webhook issues earlier.

**Pull request merged**
