### PR TITLE
swap out logger filters during capture

### LINKED ISSUE #157: LogCapture does not preserve/restore filters
https://github.com/Simplistix/testfixtures/blob/2e80aca186569cd787512eab643dbf35b14ad02a/testfixtures/logcapture.py#L147-L157

https://github.com/Simplistix/testfixtures/blob/2e80aca186569cd787512eab643dbf35b14ad02a/testfixtures/logcapture.py#L173-L178

It seems that any filters added via [`Logger.addFilter`](https://docs.python.org/3/library/logging.html#logging.Logger.addFilter) are not preserved or restored. Is this intentional?

### PR DESCRIPTION
**Pull request by rittneje**
Fixes #157.

### CODE REVIEW

**Comment by rittneje** [comment]
@cjw296 I don't have a CircleCI account so I can't see the actual failure for 2.7. If I run 2.7 locally I get this:
> testfixtures/tests/test_logcapture.py:8: in <module>
    from testfixtures.mock import Mock
E   ImportError: cannot import name Mock

But that would imply it is already broken. 😕

**Comment by cjw296** [comment]
Log in with GitHub and you'll see the test failure.
Not sure what's up with your local 2.7 env, but it's not already broken...

**Comment by rittneje** [comment]
@cjw296 In order to log in with GitHub I have to grant it write access to all my repos, which I am not comfortable doing. Can you look at it and tell me what the failure was?

**Comment by cjw296** [comment]
I find that surprising, what happens if you don't grant write access?

```
=================================== FAILURES ===================================
______________________ TestLogCapture.test_with_statement ______________________

self = <testfixtures.tests.test_logcapture.TestLogCapture testMethod=test_with_statement>

    def test_with_statement(self):
>       root.info('before')

testfixtures/tests/test_logcapture.py:273: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python2.7/logging/__init__.py:1174: in info
    self._log(INFO, msg, args, **kwargs)
/usr/local/lib/python2.7/logging/__init__.py:1293: in _log
    self.handle(record)
/usr/local/lib/python2.7/logging/__init__.py:1302: in handle
    if (not self.disabled) and self.filter(record):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <logging.RootLogger object at 0x7f630558a350>
record = <logging.LogRecord object at 0x7f6303678d50>

    def filter(self, record):
        """
        Determine if a record is loggable by consulting all the filters.
    
        The default is to allow the record to be logged; any filter can veto
        this and the record is then dropped. Returns a zero value if a record
        is to be dropped, else non-zero.
        """
        rv = 1
        for f in self.filters:
>           if not f.filter(record):
E           AttributeError: 'function' object has no attribute 'filter'

/usr/local/lib/python2.7/logging/__init__.py:617: AttributeError
```

**Comment by rittneje** [comment]
@cjw296 I can either grant read/write access to everything, or just my public repos, but there is no way to not grant write access specifically.

image
image

In any case, thanks for pasting the output; I'll look into that failure.

**Comment by cjw296** [comment]
Oh :-( 

Well, I've put this on the CircleCI discuss thing as I'm not sure it's intentional:
https://discuss.circleci.com/t/builds-in-public-oss-repos-not-visible-without-logging-in/41273

**Comment by cjw296** [comment]
Related to the test failure, are any of your projects on Py2?

**Review by cjw296 — APPROVED** [review]

**Pull request merged**
